--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    facing: front
    service: rollerrss
    type: express
  name: rollerrss-express
spec: 
  ports: 
    - 
      name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector: 
    service: rollerrss
    type: express